### PR TITLE
added /* */ comments

### PR DESCRIPTION
**Pull request by Tranberry**
probably a dirty hack but it works.

### CODE REVIEW

**Comment by Tranberry** [comment]
fixed escape symbol.

**Comment by MxAshUp** [comment]
@Tranberry thanks for opening this!

This comment syntax, isn't it only valid in css/js areas? Passages use the `<!-- -->` comment syntax, right? Maybe I need to try this out.

**Comment by MxAshUp** [comment]
I gave it a try, unless I'm missing something, it looks like twee doesn't interpret `/* ... */` as a comment:

Screenshot from 2020-08-03 08-49-03
Screenshot from 2020-08-03 08-48-56

**Comment by MxAshUp** [comment]
It looks like `/* ... */` works pretty well in passages marked as [stylesheet] or [script]
Screenshot from 2020-08-03 08-53-29

**Comment by Tranberry** [comment]
I use them in passages, perhaps it's a tweego/sugarcube thing but https://www.motoslave.net/sugarcube/2/docs/#markup-comment  states them as global.

**Comment by MxAshUp** [comment]
Hmm, this does look specific to Sugarcube. My screenshots above are with Harlowe.

Any ideas how we could make this syntax highlighting only show up for the Sugarcube format? Maybe in the extension? Sugarcube could be *.sc.twee. Or maybe a config in the director? Or passage attribute?
If we can figure that out, it might be possible to add other format-specific syntax.

**Comment by Tranberry** [comment]
perhaps you should change this line https://github.com/DustinWoods/vscode-twee2-syntax/blob/6224f65af68281a79df964f3859eece7a07e41c6/language-configuration.json#L6

to go for `<!-- -->` instead?

**Comment by MxAshUp** [comment]
Huh I wonder how that doesn't seem to affect syntax highlighting. But yeah that does seem correct.

Regarding format-specific syntax. I wonder if we could use comments at the beginning of twee2 files like this:
Screenshot from 2020-08-03 12-14-05

twee2 ignores this, and it doesn't cause any problems. What do you think?

**Comment by MxAshUp** [comment]
Or maybe instead:
```
<!-- format: SugarCube2 -->
```

**Comment by MxAshUp** [comment]
We'd need to use the `firstLineMatch` in the grammar file

**Comment by Tranberry** [comment]
I'm fine with whatever you choose to do.

My wish is that the `alt` + `shit` + `a` command generate a highlight comment block (which I believe that line control (what kind of comment to make)).

I'm new to syntax highlighting modding so my contributions will not really be coming from knowledge.

**Comment by MxAshUp** [comment]
Ohh I see, that line in language-configuration.json is what's causing `alt` + `shift` + `a` (or my case `ctrl` + `shift` + `a`) to insert `/* */`

Since  is a universal comment twee, and `/* */` is specific to SugarCube, your suggestion makes sense. So for the first fix, let's update language-configuration.json as you suggested (feel free to update PR here).

And I'll open another issue for format-specific syntax highlighting.

**Comment by MxAshUp** [comment]
related issue: #5

**Pull request closed without merging**
